# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every week"

# allow to close stale PRs
# default: True
close_prs: True
